import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Flags the standard "setLoading(true) then fetch" data-fetching
      // pattern used throughout this app's client components; too strict
      // for that idiomatic case as of this rule's current form.
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next at build time — not source.
    "public/sw.js",
    "public/swe-worker*.js",
  ]),
]);

export default eslintConfig;
